// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfZnTju8k2tluckbpp7ImaAdboTK39VUI',
    appId: '1:1087833379857:web:411ea2bfb77f0aa63c8db0',
    messagingSenderId: '1087833379857',
    projectId: 'cmsc23-todo-app-gddiocadiz',
    authDomain: 'cmsc23-todo-app-gddiocadiz.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-gddiocadiz.appspot.com',
    measurementId: 'G-B3H1KZS2EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZsPy6g0Qf13haBD1q-Aa1TVu-oxy1t0',
    appId: '1:1087833379857:android:45e9198a3036bdd73c8db0',
    messagingSenderId: '1087833379857',
    projectId: 'cmsc23-todo-app-gddiocadiz',
    storageBucket: 'cmsc23-todo-app-gddiocadiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7P3IwjUCT5UVE6SaPIQxFW0vpTzaW7Ac',
    appId: '1:1087833379857:ios:77176c518e686db43c8db0',
    messagingSenderId: '1087833379857',
    projectId: 'cmsc23-todo-app-gddiocadiz',
    storageBucket: 'cmsc23-todo-app-gddiocadiz.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7P3IwjUCT5UVE6SaPIQxFW0vpTzaW7Ac',
    appId: '1:1087833379857:ios:77176c518e686db43c8db0',
    messagingSenderId: '1087833379857',
    projectId: 'cmsc23-todo-app-gddiocadiz',
    storageBucket: 'cmsc23-todo-app-gddiocadiz.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfZnTju8k2tluckbpp7ImaAdboTK39VUI',
    appId: '1:1087833379857:web:cc9f485508b8487b3c8db0',
    messagingSenderId: '1087833379857',
    projectId: 'cmsc23-todo-app-gddiocadiz',
    authDomain: 'cmsc23-todo-app-gddiocadiz.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-gddiocadiz.appspot.com',
    measurementId: 'G-FDE4M8G326',
  );
}
